### PR TITLE
Add optional nodes

### PR DESCRIPTION
**Pull request by AndrewScibek**
Add optional pipeline nodes.

### CODE REVIEW

**Review by badtuple — CHANGES_REQUESTED** [review]
Heya, thanks for the PR!  I can definitely see the need for optional services.  I do have a couple requests though.

Would you be able to change the `optional` field to `required`?  Having a service set as required instead of optional makes working with bitmasks a bit easier because less negation is needed.

In optional_services_mask you have the line `mask |= 0 << pos`.  This will always be zero, and I don't think that's what you were intending. However if you change optional to required, then what you can do is just leave off that second condition and just only set the bit `mask |= 1 << pos` if it's required.  That way you don't have an if/else, just a single if.

A final request I have (though open to discussion) is that the log line on line 89 follow the same format as the log line on 87.  Having the words "full" and "optional" in different places conditionally makes it a bit harder for other services and log query tools to parse the information.  Edge cases often stink when you don't own the tools! If you leave off the full or optional parts and just let the bitset tell us what happened, I think it'll lead to simpler integrations.  Of course, eventually we'll wanna replace the bitset for a more user friendly output anyway.

**Comment by AndrewScibek** [comment]
Switching to required is also much clearer imo 👍 

You are totally right. I didn't notice it was being `|=` so i was manually constructing it  

I am fine removing those words, i was aiming to just make it obvious when scanning logs that there are 3 states that can happen

**Comment by AndrewScibek** [comment]
One downside to this implementation is that optional nodes at the end of pipelines will never be checked

**Comment by badtuple** [comment]
Looks good, thanks for addressing the comments.

I think the point you brought up is a non-issue because we only check if things are complete at time of expiration, not after each service checks in.  I'm going to go ahead and merge things. Thanks for the PR!

**Pull request merged**
